version: '3.8'

services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /path/to/elasticsearch/data:/var/lib/elasticsearch
    environment:
      - discovery.type=single-node

