version: '3.8'
services:
  elasticsearch:
    container_name: elasticsearch
    image: my-elasticsearch-image 
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
    driver: local

